### ISSUE TITLE
Make Contrib Avatars Equal Size

### ISSUE THREAD

**Issue by grayghostvisuals** [grayghostvisuals/transformicons#88]
In order to keep avatars the same size when one is smaller add this line to the contribs ``li``

```css
ul#tcons-contributors li {
  flex: 1
}
```
